table Cognitive_Services_Kind
	lineageTag: 7a62124e-49a4-4aab-a15d-e51d39648d46

	column kind
		dataType: string
		lineageTag: f9f7f4fe-eb42-443b-ae8a-afbbac9f01e8
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column count_type
		dataType: int64
		formatString: 0
		lineageTag: d983e038-99a8-4994-a814-9d76d1421fd6
		summarizeBy: none
		sourceColumn: count_type

		annotation SummarizationSetBy = Automatic

	partition Cognitive_Services_Kind = m
		mode: import
		queryGroup: 'Azure Resource Graph'
		source =
				let
				    Source = AzureResourceGraph.Query("resources#(lf)| where type == ""microsoft.cognitiveservices/accounts""#(lf)| where kind =~ ""OpenAI""#(lf)| summarize count(type) by kind", "Tenant", null, null, [resultTruncated=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"count_type", Int64.Type}, {"kind", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

