table OpenAI_By_ResourceGroup
	lineageTag: 72da6603-3c63-4434-8b0f-d72dc0a9f1f5

	column resourceGroup
		dataType: string
		lineageTag: c39d5205-eb73-4245-9a67-5b57051168e8
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column count_type
		dataType: int64
		formatString: 0
		lineageTag: 36170be7-7772-4b2a-8a07-36b7ccaa8e9b
		summarizeBy: sum
		sourceColumn: count_type

		annotation SummarizationSetBy = Automatic

	partition OpenAI_By_ResourceGroup = m
		mode: import
		queryGroup: 'Azure Resource Graph'
		source =
				let
				    Source = AzureResourceGraph.Query("resources#(lf)| where type =~ ""microsoft.cognitiveservices/accounts""#(lf)| where kind =~ ""OpenAI""#(lf)| summarize count(type) by resourceGroup", "Tenant", null, null, [resultTruncated=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"count_type", Int64.Type}, {"resourceGroup", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

