table OpenAI_By_Region
	lineageTag: d6f0978e-d4e1-4f6e-8612-a7a7649daff5

	column location
		dataType: string
		lineageTag: 94573cbd-9cc4-4357-abbd-b15036b7fc3f
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column count_type
		dataType: int64
		formatString: 0
		lineageTag: 2a890533-7b50-49b9-9f5f-d7ca44561cbf
		summarizeBy: none
		sourceColumn: count_type

		annotation SummarizationSetBy = Automatic

	partition OpenAI_By_Region = m
		mode: import
		queryGroup: 'Azure Resource Graph'
		source =
				let
				    Source = AzureResourceGraph.Query("resources#(lf)| where type =~ ""microsoft.cognitiveservices/accounts""#(lf)| where kind =~ ""OpenAI""#(lf)| summarize count(type) by location#(lf)", "Tenant", null, null, [resultTruncated=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"count_type", Int64.Type}, {"location", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

