table OpenAI_By_SubscriptionId
	lineageTag: 9b331a69-a444-44e4-ab14-8612eacbc7d8

	column subscriptionId
		dataType: string
		lineageTag: 3d3e0f5a-bc5c-4204-82ea-410e09c947d1
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column count_type
		dataType: int64
		formatString: 0
		lineageTag: 3c5e0210-6673-4732-bf15-7c9836c9e606
		summarizeBy: sum
		sourceColumn: count_type

		annotation SummarizationSetBy = Automatic

	partition OpenAI_By_SubscriptionId = m
		mode: import
		queryGroup: 'Azure Resource Graph'
		source =
				let
				    Source = AzureResourceGraph.Query("resources#(lf)| where type =~ ""microsoft.cognitiveservices/accounts""#(lf)| where kind =~ ""OpenAI""#(lf)| summarize count(type) by subscriptionId", "Tenant", null, null, [resultTruncated=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"count_type", Int64.Type}, {"subscriptionId", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

