table Operational_Insights
	lineageTag: 2725f98e-1a56-4882-8ad3-9a5763c2428c

	column value
		dataType: string
		lineageTag: bcc01e64-1568-407f-a88f-5874e05e737d
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column label
		dataType: string
		lineageTag: 5bcb2c92-594f-4aeb-8c63-9f7c4a336526
		summarizeBy: none
		sourceColumn: label

		annotation SummarizationSetBy = Automatic

	column selected
		dataType: int64
		formatString: 0
		lineageTag: 084d6a58-2eb5-4dee-8c8d-b0208f077729
		summarizeBy: sum
		sourceColumn: selected

		annotation SummarizationSetBy = Automatic

	partition Operational_Insights = m
		mode: import
		queryGroup: 'Azure Resource Graph'
		source =
				let
				    Source = AzureResourceGraph.Query("Resources#(lf)| where type =~ ""microsoft.operationalinsights/workspaces""#(lf)| summarize Count = count() by subscriptionId#(lf)| order by Count desc#(lf)| extend Rank = row_number()#(lf)| project value = subscriptionId, label = subscriptionId, selected = Rank == 1", "Tenant", null, null, [resultTruncated=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"value", type text}, {"label", type text}, {"selected", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

